# This is a basic workflow to help you get started with Actions

name: Deploy My Server
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: node20
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: https://gitea.com/actions/checkout@v4
      # 安装pnpm
      - name: Install pnpm
        run: npm install -g pnpm
      # pnpm安装依赖
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      # 打包
      - name: Build
        run: npm run build
        # 创建.ssh文件夹 并写入私钥
      - name: Write ssh key
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: mkdir -p ~/.ssh && echo "$PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      - name: Add known_hosts
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
      - name: echo pwd
        run: pwd
        # 运行 sh ./cmd/publish.sh 脚本
      - name: Deploy
        run: sh ./cmd/publish.sh